name: ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: docker.io
  APP_NAME: ${{ github.event.repository.name }}
  DOCKERHUB_REPO: itzmiracle/discord-avatar-api
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
